// api/info.js
// ============================================================
// DICTIONNAIRE DES CATÉGORIES (copié depuis index.html)
// ============================================================
const DOMAIN_CATEGORY = {
  "bandwidth.depin": "Réseau & Connectivité",
  "gateway.depin": "Réseau & Connectivité",
  "internet.depin": "Réseau & Connectivité",
  "network.depin": "Réseau & Connectivité",
  "network.rwa": "Réseau & Connectivité",
  "node.depin": "Réseau & Connectivité",
  "spectrum.depin": "Réseau & Connectivité",
  "telecom.depin": "Réseau & Connectivité",
  "telecom.rwa": "Réseau & Connectivité",
  "constellation.rwa": "Réseau & Connectivité",
  "constellation.depin": "Réseau & Connectivité",
  "satellite.rwa": "Réseau & Connectivité",
  "satellite.depin": "Réseau & Connectivité",
  "battery.depin": "Énergie & Ressources",
  "battery.rwa": "Énergie & Ressources",
  "carbon.depin": "Énergie & Ressources",
  "carbon.rlusd": "Énergie & Ressources",
  "crudeoil.depin": "Énergie & Ressources",
  "crudeoil.rwa": "Énergie & Ressources",
  "energie.xdc": "Énergie & Ressources",
  "energy.depin": "Énergie & Ressources",
  "energy.rlusd": "Énergie & Ressources",
  "petroleum.depin": "Énergie & Ressources",
  "petroleum.rwa": "Énergie & Ressources",
  "pipeline.depin": "Énergie & Ressources",
  "pipeline.rwa": "Énergie & Ressources",
  "pipeline.xdc": "Énergie & Ressources",
  "thorium.depin": "Énergie & Ressources",
  "энергия.depin": "Énergie & Ressources",
  "энергия.rwa": "Énergie & Ressources",
  "энергия.xdc": "Énergie & Ressources",
  "3dprinter.depin": "Calcul & IA",
  "compute.depin": "Calcul & IA",
  "compute.rlusd": "Calcul & IA",
  "compute.rwa": "Calcul & IA",
  "compute.xdc": "Calcul & IA",
  "compute.xrp": "Calcul & IA",
  "computer.depin": "Calcul & IA",
  "computer.rwa": "Calcul & IA",
  "datacenter.depin": "Calcul & IA",
  "datacenter.rwa": "Calcul & IA",
  "deeplearning.xdc": "Calcul & IA",
  "motherboard.xdc": "Calcul & IA",
  "ordinateur.xdc": "Calcul & IA",
  "quantum.depin": "Calcul & IA",
  "storage.depin": "Calcul & IA",
  "storage.rwa": "Calcul & IA",
  "argent.xdc": "Finance & Liquidité",
  "asset.depin": "Finance & Liquidité",
  "banking.depin": "Finance & Liquidité",
  "banking.rlusd": "Finance & Liquidité",
  "banking.rwa": "Finance & Liquidité",
  "bourse.xdc": "Finance & Liquidité",
  "compliance.depin": "Finance & Liquidité",
  "compliance.rwa": "Finance & Liquidité",
  "finance.depin": "Finance & Liquidité",
  "gold.rlusd": "Finance & Liquidité",
  "liquidity.depin": "Finance & Liquidité",
  "liquidity.rlusd": "Finance & Liquidité",
  "liquidity.rwa": "Finance & Liquidité",
  "mortgage.depin": "Finance & Liquidité",
  "payments.depin": "Finance & Liquidité",
  "payments.rlusd": "Finance & Liquidité",
  "payments.rwa": "Finance & Liquidité",
  "stablecoin.depin": "Finance & Liquidité",
  "stablecoin.rwa": "Finance & Liquidité",
  "trade.depin": "Finance & Liquidité",
  "финансы.xdc": "Finance & Liquidité",
  "debt.rwa": "Finance & Liquidité",
  "debt.depin": "Finance & Liquidité",
  "settlement.rwa": "Finance & Liquidité",
  "agents.xdc": "Identité & Gouvernance",
  "bodyguard.xdc": "Identité & Gouvernance",
  "defense.depin": "Identité & Gouvernance",
  "defense.rwa": "Identité & Gouvernance",
  "foundation.depin": "Identité & Gouvernance",
  "governance.depin": "Identité & Gouvernance",
  "governance.rwa": "Identité & Gouvernance",
  "identity.depin": "Identité & Gouvernance",
  "justice.rwa": "Identité & Gouvernance",
  "justice.depin": "Identité & Gouvernance",
  "lawyer.depin": "Identité & Gouvernance",
  "legacy.depin": "Identité & Gouvernance",
  "numident.rwa": "Identité & Gouvernance",
  "osint.depin": "Identité & Gouvernance",
  "passport.depin": "Identité & Gouvernance",
  "passport.rwa": "Identité & Gouvernance",
  "security.depin": "Identité & Gouvernance",
  "security.rwa": "Identité & Gouvernance",
  "numident.xdc": "Identité & Gouvernance",
  "numident.depin": "Identité & Gouvernance",
  "aircraft.depin": "Immobilier & Logistique",
  "aircraft.rwa": "Immobilier & Logistique",
  "chokepoint.depin": "Immobilier & Logistique",
  "chokepoint.rwa": "Immobilier & Logistique",
  "croisieres.xdc": "Immobilier & Logistique",
  "immobilier.depin": "Immobilier & Logistique",
  "immobilier.xdc": "Immobilier & Logistique",
  "immobilier.xrp": "Immobilier & Logistique",
  "logistics.depin": "Immobilier & Logistique",
  "maritime.depin": "Immobilier & Logistique",
  "mobility.depin": "Immobilier & Logistique",
  "mobility.rwa": "Immobilier & Logistique",
  "mobility.xdc": "Immobilier & Logistique",
  "navigation.depin": "Immobilier & Logistique",
  "navigation.rwa": "Immobilier & Logistique",
  "navigation.xdc": "Immobilier & Logistique",
  "realestate.depin": "Immobilier & Logistique",
  "shipping.depin": "Immobilier & Logistique",
  "smartcity.depin": "Immobilier & Logistique",
  "smartcity.rwa": "Immobilier & Logistique",
  "supplychain.depin": "Immobilier & Logistique",
  "supplychain.rwa": "Immobilier & Logistique",
  "voiture.xdc": "Immobilier & Logistique",
  "voitures.xdc": "Immobilier & Logistique",
  "yacht.depin": "Immobilier & Logistique",
  "yacht.rwa": "Immobilier & Logistique",
  "عقارات.depin": "Immobilier & Logistique",
  "عقارات.rwa": "Immobilier & Logistique",
  "عقارات.xdc": "Immobilier & Logistique",
  "agriculture.depin": "Agriculture & Alimentation",
  "agriculture.rwa": "Agriculture & Alimentation",
  "baguette.xdc": "Agriculture & Alimentation",
  "boucherie.xdc": "Agriculture & Alimentation",
  "boulangerie.xdc": "Agriculture & Alimentation",
  "cheese.depin": "Agriculture & Alimentation",
  "cheese.rwa": "Agriculture & Alimentation",
  "cheese.xdc": "Agriculture & Alimentation",
  "coffee.depin": "Agriculture & Alimentation",
  "coffee.rwa": "Agriculture & Alimentation",
  "foiegras.depin": "Agriculture & Alimentation",
  "foiegras.rwa": "Agriculture & Alimentation",
  "foiegras.xdc": "Agriculture & Alimentation",
  "fromage.xdc": "Agriculture & Alimentation",
  "protein.xdc": "Agriculture & Alimentation",
  "saffron.depin": "Agriculture & Alimentation",
  "saffron.rwa": "Agriculture & Alimentation",
  "saffron.xdc": "Agriculture & Alimentation",
  "shrimp.depin": "Agriculture & Alimentation",
  "shrimp.rwa": "Agriculture & Alimentation",
  "shrimp.xdc": "Agriculture & Alimentation",
  "soybeans.rwa": "Agriculture & Alimentation",
  "spices.xdc": "Agriculture & Alimentation",
  "truffle.depin": "Agriculture & Alimentation",
  "truffle.rwa": "Agriculture & Alimentation",
  "truffle.xdc": "Agriculture & Alimentation",
  "food.rwa": "Agriculture & Alimentation",
  "food.depin": "Agriculture & Alimentation",
  "supermarket.rwa": "Agriculture & Alimentation",
  "supermarket.depin": "Agriculture & Alimentation",
  "tabac.xdc": "Agriculture & Alimentation",
  "tobacco.xrp": "Agriculture & Alimentation",
  "aluminum.depin": "Métaux & Luxe",
  "aluminum.rwa": "Métaux & Luxe",
  "copper.xrp": "Métaux & Luxe",
  "emerald.depin": "Métaux & Luxe",
  "emerald.rwa": "Métaux & Luxe",
  "emerald.xdc": "Métaux & Luxe",
  "emerald.xrp": "Métaux & Luxe",
  "gemstone.xrp": "Métaux & Luxe",
  "jewel.xdc": "Métaux & Luxe",
  "necklace.xdc": "Métaux & Luxe",
  "platinium.xdc": "Métaux & Luxe",
  "rings.xdc": "Métaux & Luxe",
  "ruby.xdc": "Métaux & Luxe",
  "sapphire.depin": "Métaux & Luxe",
  "sapphire.rwa": "Métaux & Luxe",
  "sapphire.xdc": "Métaux & Luxe",
  "sapphire.xrp": "Métaux & Luxe",
  "алмаз.depin": "Métaux & Luxe",
  "алмаз.rwa": "Métaux & Luxe",
  "алмаз.xdc": "Métaux & Luxe",
  "золото.depin": "Métaux & Luxe",
  "золото.rwa": "Métaux & Luxe",
  "золото.xdc": "Métaux & Luxe",
  "ذهب.xdc": "Métaux & Luxe",
  "металлы.depin": "Métaux & Luxe",
  "металлы.rwa": "Métaux & Luxe",
  "металлы.xdc": "Métaux & Luxe",
  "armagnac.depin": "Vins & Spiritueux",
  "armagnac.rwa": "Vins & Spiritueux",
  "armagnac.xdc": "Vins & Spiritueux",
  "champagne.depin": "Vins & Spiritueux",
  "champagne.rwa": "Vins & Spiritueux",
  "champagne.xrp": "Vins & Spiritueux",
  "ricard.xdc": "Vins & Spiritueux",
  "tequila.depin": "Vins & Spiritueux",
  "tequila.rwa": "Vins & Spiritueux",
  "tequila.xdc": "Vins & Spiritueux",
  "aloevera.depin": "Santé",
  "aloevera.rwa": "Santé",
  "aloevera.xdc": "Santé",
  "health.depin": "Santé",
  "health.rwa": "Santé",
  "pharmacie.xdc": "Santé",
  "wellbeing.depin": "Santé",
  "healthcare.depin": "Santé",
  "neurlink.depin": "Santé",
  "neuralink.rwa": "Santé",
  "biometric.rwa": "Santé",
  "biometric.depin": "Santé",
  "alphabet.depin": "Culture & Langues",
  "astronomy.depin": "Culture & Langues",
  "bibliothèque.xdc": "Culture & Langues",
  "dictionary.depin": "Culture & Langues",
  "encyclopedia.depin": "Culture & Langues",
  "genealogy.xdc": "Culture & Langues",
  "histoire.xdc": "Culture & Langues",
  "library.depin": "Culture & Langues",
  "library.rwa": "Culture & Langues",
  "logos.depin": "Culture & Langues",
  "mathematics.depin": "Culture & Langues",
  "physics.depin": "Culture & Langues",
  "pinyin.depin": "Culture & Langues",
  "pinyin.rwa": "Culture & Langues",
  "pinyin.xdc": "Culture & Langues",
  "school.depin": "Culture & Langues",
  "telescope.xdc": "Culture & Langues",
  "unicode.depin": "Culture & Langues",
  "unicode.rwa": "Culture & Langues",
  "unicode.xdc": "Culture & Langues",
  "university.depin": "Culture & Langues",
  "cinema.rwa": "Culture & Langues",
  "cinema.depin": "Culture & Langues",
  "travel.rwa": "Culture & Langues",
  "travel.depin": "Culture & Langues",
  "magazine.rwa": "Culture & Langues",
  "magazine.depin": "Culture & Langues",
  "africa.depin": "Territoires",
  "asia.depin": "Territoires",
  "bordeaux.xdc": "Territoires",
  "california.depin": "Territoires",
  "france.depin": "Territoires",
  "french.xdc": "Territoires",
  "français.xdc": "Territoires",
  "gallia.depin": "Territoires",
  "gallia.rwa": "Territoires",
  "gallia.xdc": "Territoires",
  "gascogne.xdc": "Territoires",
  "global.depin": "Territoires",
  "global.rwa": "Territoires",
  "globalstore.xdc": "Territoires",
  "greenland.depin": "Territoires",
  "helsinki.xdc": "Territoires",
  "latvia.depin": "Territoires",
  "latvia.rwa": "Territoires",
  "latvia.xdc": "Territoires",
  "latvija.depin": "Territoires",
  "latvija.rwa": "Territoires",
  "latvija.xdc": "Territoires",
  "monaco.depin": "Territoires",
  "northamerica.depin": "Territoires",
  "northamerica.rwa": "Territoires",
  "oceania.depin": "Territoires",
  "russia.depin": "Territoires",
  "singapore.depin": "Territoires",
  "singapore.rwa": "Territoires",
  "thailand.depin": "Territoires",
  "thailand.rwa": "Territoires",
  "web3hexagone.xdc": "Territoires",
  "دولة-قطر.xdc": "Territoires",
  "دولةقطر.xdc": "Territoires",
  "vatican.depin": "Territoires",
  "artgallery.depin": "Médias & Art",
  "artgallery.rwa": "Médias & Art",
  "artgallery.xdc": "Médias & Art",
  "broadcast.depin": "Médias & Art",
  "broadcast.rwa": "Médias & Art",
  "casino.depin": "Médias & Art",
  "design.depin": "Médias & Art",
  "gambler.xdc": "Médias & Art",
  "gambler.xrp": "Médias & Art",
  "gaming.depin": "Médias & Art",
  "gaming.rwa": "Médias & Art",
  "guitar.rwa": "Médias & Art",
  "guitar.xrp": "Médias & Art",
  "manga.xrp": "Médias & Art",
  "media.depin": "Médias & Art",
  "music.rwa": "Médias & Art",
  "musique.xrp": "Médias & Art",
  "paint.xdc": "Médias & Art",
  "photographe.xdc": "Médias & Art",
  "photographe.xrp": "Médias & Art",
  "photographer.xrp": "Médias & Art",
  "streamer.xrp": "Médias & Art",
  "streaming.depin": "Médias & Art",
  "streaming.rwa": "Médias & Art",
  "streaming.xdc": "Médias & Art",
  "streaming.xrp": "Médias & Art",
  "studio.depin": "Médias & Art",
  "studio.rwa": "Médias & Art",
  "9thcircle.depin": "Lore & Mythes",
  "alucard.xdc": "Lore & Mythes",
  "angels.xdc": "Lore & Mythes",
  "apocalypse.depin": "Lore & Mythes",
  "arcadia.depin": "Lore & Mythes",
  "babylon.depin": "Lore & Mythes",
  "castle.xrp": "Lore & Mythes",
  "cryptomancer.xdc": "Lore & Mythes",
  "deathnote.depin": "Lore & Mythes",
  "dieu.xdc": "Lore & Mythes",
  "fleursdelys.xdc": "Lore & Mythes",
  "freemasonry.depin": "Lore & Mythes",
  "guilde.xdc": "Lore & Mythes",
  "heracles.xdc": "Lore & Mythes",
  "jeannedarc.xdc": "Lore & Mythes",
  "jerusalem.depin": "Lore & Mythes",
  "jerusalem.rwa": "Lore & Mythes",
  "katana.depin": "Lore & Mythes",
  "katana.rwa": "Lore & Mythes",
  "katana.xdc": "Lore & Mythes",
  "legion.xdc": "Lore & Mythes",
  "licorne.xdc": "Lore & Mythes",
  "maitreya.xrp": "Lore & Mythes",
  "mallworld.xdc": "Lore & Mythes",
  "medusa.xdc": "Lore & Mythes",
  "mythology.xdc": "Lore & Mythes",
  "mythology.xrp": "Lore & Mythes",
  "nemesis.xdc": "Lore & Mythes",
  "nostradamus.xdc": "Lore & Mythes",
  "perseus.xdc": "Lore & Mythes",
  "prometheus.xdc": "Lore & Mythes",
  "religion.depin": "Lore & Mythes",
  "revelation.xrp": "Lore & Mythes",
  "scorpio.xdc": "Lore & Mythes",
  "scorpion.xdc": "Lore & Mythes",
  "singularity.depin": "Lore & Mythes",
  "singularity.rwa": "Lore & Mythes",
  "singularity.xdc": "Lore & Mythes",
  "suntsu.xdc": "Lore & Mythes",
  "suntzu.xdc": "Lore & Mythes",
  "tarot.xdc": "Lore & Mythes",
  "tartaria.depin": "Lore & Mythes",
  "tesseract.xdc": "Lore & Mythes",
  "voodoo.xdc": "Lore & Mythes",
  "zodiac.depin": "Lore & Mythes",
  "القرآن.xdc": "Lore & Mythes",
  "लक्ष्मी.xdc": "Lore & Mythes",
  "पार्वती.xdc": "Lore & Mythes",
  "सरस्वती.xdc": "Lore & Mythes",
  "त्रिदेवी.xdc": "Lore & Mythes",
  "⚜️⚜️⚜️.xdc": "Lore & Mythes",
  "ar-lenses.xdc": "Hardware & Capteurs",
  "arlenses.xdc": "Hardware & Capteurs",
  "camera.rwa": "Hardware & Capteurs",
  "camera.xrp": "Hardware & Capteurs",
  "controller.depin": "Hardware & Capteurs",
  "controller.rwa": "Hardware & Capteurs",
  "controller.xdc": "Hardware & Capteurs",
  "drones.depin": "Hardware & Capteurs",
  "exoskeleton.depin": "Hardware & Capteurs",
  "exoskeleton.rwa": "Hardware & Capteurs",
  "exoskeleton.xdc": "Hardware & Capteurs",
  "focalzero.xdc": "Hardware & Capteurs",
  "hashish.xdc": "Hardware & Capteurs",
  "laptop.xrp": "Hardware & Capteurs",
  "nature.depin": "Hardware & Capteurs",
  "phone.xrp": "Hardware & Capteurs",
  "phones.xrp": "Hardware & Capteurs",
  "robotic.depin": "Hardware & Capteurs",
  "robotic.rwa": "Hardware & Capteurs",
  "satellite.depin": "Hardware & Capteurs",
  "satellite.rwa": "Hardware & Capteurs",
  "sensor.depin": "Hardware & Capteurs",
  "sensor.rwa": "Hardware & Capteurs",
  "sensor.xdc": "Hardware & Capteurs",
  "speaker.xdc": "Hardware & Capteurs",
  "motorcycle.rwa": "Hardware & Capteurs",
  "motorcycle.depin": "Hardware & Capteurs",
  "software.rwa": "Hardware & Capteurs",
  "software.depin": "Hardware & Capteurs",
  "cyborg.rwa": "Hardware & Capteurs",
  "cyborg.depin": "Hardware & Capteurs",
  "gigafactory.rwa": "Hardware & Capteurs",
  "gigafactory.depin": "Hardware & Capteurs",
  "factory.depin": "Hardware & Capteurs",
  "shipping.rwa": "Hardware & Capteurs",
  "maritime.rwa": "Hardware & Capteurs"
};

// ============================================================
// FONCTION DE CATÉGORISATION (avec héritage)
// ============================================================
function getCategory(domain) {
    if (!domain) return null;
    const d = domain.toLowerCase();
    if (DOMAIN_CATEGORY[d]) return DOMAIN_CATEGORY[d];
    let parts = d.split('.');
    while (parts.length > 1) {
        parts.shift();
        const parent = parts.join('.');
        if (DOMAIN_CATEGORY[parent]) return DOMAIN_CATEGORY[parent];
    }
    if (d.endsWith('.xdc')) return "Domaine XDC";
    if (d.endsWith('.rwa')) return "Real World Asset";
    if (d.endsWith('.depin')) return "DePIN";
    return null;
}

// ============================================================
// ENDPOINT /api/info (UNIQUE, avec copyright)
// ============================================================
export default async function handler(req, res) {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Cache-Control', 'no-store');

    const { domain } = req.query;
    if (!domain) return res.status(400).json({ error: 'Domaine manquant' });

    const resolveUrl = `https://fleurs-resolver-final.vercel.app/api/resolve?domain=${encodeURIComponent(domain)}`;
    try {
        const resolveRes = await fetch(resolveUrl);
        const resolveData = await resolveRes.json();
        if (!resolveData.result) {
            return res.status(404).json({ error: 'Domaine non trouvé' });
        }
        const category = getCategory(domain);
        const response = {
            domain,
            address: resolveData.result,
            category: category || null,
            assetType: category ? 'SemanticAsset' : null,
            endpoints: {
                info: `/api/info?domain=${encodeURIComponent(domain)}`,
                invoice: `/api/invoice?domain=${encodeURIComponent(domain)}`,
                status: '/api/status'
            },
            copyright: "© 2026 Fleurs de Lys / FocalZero – Tous droits réservés – Licence SAN-2026.1"
        };
        res.status(200).json(response);
    } catch (err) {
        console.error(err);
        res.status(500).json({ error: 'Erreur serveur' });
    }
}